### ISSUE TITLE
Beaker crashes when accessing dataset

### ISSUE THREAD

**Issue by despens** [beakerbrowser/beakerbrowser.com#77] opened 2018-06-20 15:15 UTC
The dataset dat://386ef60e56eb9edb878738ee35ee6e95c8552902985e725a5901ae6851e25d00/ causes Beaker to freeze and then crash when it is loaded.

CPU usage goes to 100% before, the interface becomes unresponsive.

I'm using beaker-browser-0.8.0-prerelease.6-x86_64.AppImage on Ubuntu 18.04

**Comment by pfrazee** [comment] 2018-06-20 16:21
Closing as a duplicate of https://github.com/beakerbrowser/beaker/issues/1030. Next version of Dat will have some performance improvements that should stop this from happening.

**Closed as completed by pfrazee** 2018-06-20 16:21 UTC
Labels: duplicate
